
DROP VIEW IF EXISTS "STUDENTSERVICE_STUDENTS";
DROP VIEW IF EXISTS "BATCHSERVICE_BRANCHES";
DROP VIEW IF EXISTS "BATCHSERVICE_BATCHES";
DROP VIEW IF EXISTS "BATCHSERVICE_COURSES";
DROP VIEW IF EXISTS "BATCHSERVICE_SUBJECTS";
DROP VIEW IF EXISTS "COACHINGSERVICE_BATCHES";
DROP VIEW IF EXISTS "COACHINGSERVICE_BRANCHES";
DROP VIEW IF EXISTS "COACHINGSERVICE_COURSES";
DROP VIEW IF EXISTS "COACHINGSERVICE_SUBJECTS";
DROP VIEW IF EXISTS "COACHINGSERVICE_STUDENTS";
DROP VIEW IF EXISTS "TEACHERSERVICE_TEACHERS";
DROP VIEW IF EXISTS "ENROLLMENTSERVICE_ENROLLMENTS";
DROP VIEW IF EXISTS "ENROLLMENTSERVICE_FEEPAYMENTS";

-- Drop tables
DROP TABLE IF EXISTS "COACHING_FEEPAYMENTS";
DROP TABLE IF EXISTS "COACHING_ENROLLMENTS";
DROP TABLE IF EXISTS "COACHING_TEACHERBATCHASSIGNMENTS";
DROP TABLE IF EXISTS "COACHING_TEACHERSUBJECTS";
DROP TABLE IF EXISTS "COACHING_TEACHERS";
DROP TABLE IF EXISTS "COACHING_STUDENTS";
DROP TABLE IF EXISTS "COACHING_BATCHES";
DROP TABLE IF EXISTS "COACHING_COURSES";
DROP TABLE IF EXISTS "COACHING_SUBJECTS";
DROP TABLE IF EXISTS "COACHING_BRANCHES";
DROP TABLE IF EXISTS "CDS_OUTBOX_MESSAGES";

-- Branches
CREATE TABLE "COACHING_BRANCHES" (
    "ID"          VARCHAR(36)    NOT NULL PRIMARY KEY,
    "CREATEDAT"   TIMESTAMP,
    "CREATEDBY"   VARCHAR(255),
    "MODIFIEDAT"  TIMESTAMP,
    "MODIFIEDBY"  VARCHAR(255),
    "BRANCHCODE"  VARCHAR(10),
    "NAME"        VARCHAR(80),
    "CITY"        VARCHAR(60),
    "ACTIVE"      BOOLEAN        DEFAULT TRUE
);

-- Courses
CREATE TABLE "COACHING_COURSES" (
    "ID"              VARCHAR(36)    NOT NULL PRIMARY KEY,
    "CREATEDAT"       TIMESTAMP,
    "CREATEDBY"       VARCHAR(255),
    "MODIFIEDAT"      TIMESTAMP,
    "MODIFIEDBY"      VARCHAR(255),
    "COURSECODE"      VARCHAR(12),
    "NAME"            VARCHAR(100),
    "TARGETEXAM"      VARCHAR(50),
    "DURATIONMONTHS"  INTEGER,
    "TOTALFEES"       DECIMAL(10,2)
);

-- Subjects
CREATE TABLE "COACHING_SUBJECTS" (
    "ID"          VARCHAR(36)    NOT NULL PRIMARY KEY,
    "CREATEDAT"   TIMESTAMP,
    "CREATEDBY"   VARCHAR(255),
    "MODIFIEDAT"  TIMESTAMP,
    "MODIFIEDBY"  VARCHAR(255),
    "CODE"        VARCHAR(10),
    "NAME"        VARCHAR(80)
);

-- Batches
CREATE TABLE "COACHING_BATCHES" (
    "ID"           VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"    TIMESTAMP,
    "CREATEDBY"    VARCHAR(255),
    "MODIFIEDAT"   TIMESTAMP,
    "MODIFIEDBY"   VARCHAR(255),
    "BATCHCODE"    VARCHAR(20),
    "STARTDATE"    DATE,
    "TIMING"       VARCHAR(50),
    "MAXSTRENGTH"  INTEGER       DEFAULT 60,
    "BRANCH_ID"    VARCHAR(36),
    "COURSE_ID"    VARCHAR(36),
    FOREIGN KEY ("BRANCH_ID") REFERENCES "COACHING_BRANCHES"("ID"),
    FOREIGN KEY ("COURSE_ID") REFERENCES "COACHING_COURSES"("ID")
);

-- Students
CREATE TABLE "COACHING_STUDENTS" (
    "ID"          VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"   TIMESTAMP,
    "CREATEDBY"   VARCHAR(255),
    "MODIFIEDAT"  TIMESTAMP,
    "MODIFIEDBY"  VARCHAR(255),
    "ADMISSIONNO" VARCHAR(20),
    "FULLNAME"    VARCHAR(90),
    "PHONE"       VARCHAR(15),
    "PARENTPHONE" VARCHAR(15),
    "BRANCH_ID"   VARCHAR(36),
    FOREIGN KEY ("BRANCH_ID") REFERENCES "COACHING_BRANCHES"("ID")
);

-- Teachers
CREATE TABLE "COACHING_TEACHERS" (
    "ID"           VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"    TIMESTAMP,
    "CREATEDBY"    VARCHAR(255),
    "MODIFIEDAT"   TIMESTAMP,
    "MODIFIEDBY"   VARCHAR(255),
    "EMPCODE"      VARCHAR(12),
    "FULLNAME"     VARCHAR(90),
    "PHONE"        VARCHAR(15),
    "EMAIL"        VARCHAR(120),
    "JOININGDATE"  DATE,
    "ACTIVE"       BOOLEAN       DEFAULT TRUE
);

-- Teacher Subjects
CREATE TABLE "COACHING_TEACHERSUBJECTS" (
    "ID"          VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"   TIMESTAMP,
    "CREATEDBY"   VARCHAR(255),
    "MODIFIEDAT"  TIMESTAMP,
    "MODIFIEDBY"  VARCHAR(255),
    "TEACHER_ID"  VARCHAR(36),
    "SUBJECT_ID"  VARCHAR(36),
    FOREIGN KEY ("TEACHER_ID") REFERENCES "COACHING_TEACHERS"("ID"),
    FOREIGN KEY ("SUBJECT_ID") REFERENCES "COACHING_SUBJECTS"("ID")
);

-- Teacher Batch Assignments
CREATE TABLE "COACHING_TEACHERBATCHASSIGNMENTS" (
    "ID"           VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"    TIMESTAMP,
    "CREATEDBY"    VARCHAR(255),
    "MODIFIEDAT"   TIMESTAMP,
    "MODIFIEDBY"   VARCHAR(255),
    "TEACHER_ID"   VARCHAR(36),
    "BATCH_ID"     VARCHAR(36),
    "ROLE"         VARCHAR(30)   DEFAULT 'main',
    "ASSIGNEDON"   DATE,
    FOREIGN KEY ("TEACHER_ID") REFERENCES "COACHING_TEACHERS"("ID"),
    FOREIGN KEY ("BATCH_ID")   REFERENCES "COACHING_BATCHES"("ID")
);

-- Enrollments
CREATE TABLE "COACHING_ENROLLMENTS" (
    "ID"          VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"   TIMESTAMP,
    "CREATEDBY"   VARCHAR(255),
    "MODIFIEDAT"  TIMESTAMP,
    "MODIFIEDBY"  VARCHAR(255),
    "STUDENT_ID"  VARCHAR(36),
    "BATCH_ID"    VARCHAR(36),
    "ENROLLDATE"  DATE,
    "TOTALFEES"   DECIMAL(10,2),
    "FINALFEES"   DECIMAL(10,2),
    "STATUS"      VARCHAR(20)   DEFAULT 'active',
    FOREIGN KEY ("STUDENT_ID") REFERENCES "COACHING_STUDENTS"("ID"),
    FOREIGN KEY ("BATCH_ID")   REFERENCES "COACHING_BATCHES"("ID")
);

-- Fee Payments
CREATE TABLE "COACHING_FEEPAYMENTS" (
    "ID"             VARCHAR(36)   NOT NULL PRIMARY KEY,
    "CREATEDAT"      TIMESTAMP,
    "CREATEDBY"      VARCHAR(255),
    "MODIFIEDAT"     TIMESTAMP,
    "MODIFIEDBY"     VARCHAR(255),
    "ENROLLMENT_ID"  VARCHAR(36),
    "AMOUNT"         DECIMAL(10,2),
    "PAYMENTDATE"    DATE,
    "MODE"           VARCHAR(30),
    "RECEIPTNO"      VARCHAR(20),
    FOREIGN KEY ("ENROLLMENT_ID") REFERENCES "COACHING_ENROLLMENTS"("ID")
);

-- CDS Outbox
CREATE TABLE "CDS_OUTBOX_MESSAGES" (
    "ID"           VARCHAR(36)    NOT NULL PRIMARY KEY,
    "TIMESTAMP"    TIMESTAMP,
    "TARGET"       VARCHAR(255),
    "MSG_ID"       VARCHAR(36),
    "ATTEMPTS"     INTEGER        DEFAULT 0,
    "LAST_ATTEMPT" TIMESTAMP,
    "LAST_ERROR"   VARCHAR(5000)
);

